name: 'PR Parser'
description: 'Parses github PRs for environment variables and exports them'
author: 'EchelonFour'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'truck'
  color: 'purple'
