name: 'PR Parser'
description: 'Parses github PRs for environment variables and exports them'
author: 'EchelonFour'
inputs:
  token:
    description: 'Github token for reading PR, defaults to using secrets.GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
  additionalExtensions:
    description: 'comma separated list of file types to load into environment'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'truck'
  color: 'purple'
