name: 'PR Parser'
description: 'Parses github PRs for environment variables and exports them'
author: 'EchelonFour'
inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'key'
  color: 'purple'
