name: Check dist/

on:
  pull_request:
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest

    steps:
      - uses: EchelonFour/pr-parser@main
        with:
          additionalExtensions: bingbong,txt
      - run: echo $SOMETHING_IN_THE_PR
      - run: echo $SOMETHING_ELSE_IN_THE_PR
      - run: echo $SOMETHING_JSON_IN_THE_PR
